#!/bin/sh -e

/usr/local/bin/gotemp -f /etc/frps.ini.tpl -o /etc/frps.ini

sv start portmanager || exit 1

if [ ! -z "${FRPS_LETSENCRYPT_EMAIL}" ]; then

sv start acmeproxy || exit 1

fi

exec /usr/local/bin/frps -c /etc/frps.ini 2>&1
